MP/ Create physical address table and model
WeDevelop-ARG/cg-backend pull request #59
Opened 2020-10-16 20:14 UTC by MPucheta

2020-10-16 20:15 UTC, roke77 approved these changes

2020-10-19 14:21 UTC, nahudalla requested changes

2020-10-19 14:21 UTC, nahudalla commented on src/models/physicalAddress.js
> +    }
These are not needed in the model.

2020-10-19 15:47 UTC, nahudalla approved these changes

2020-10-19 15:47 UTC, merged