MP/ Add person model, table and relationships
WeDevelop-ARG/cg-backend pull request #61
Opened 2020-10-19 15:56 UTC by MPucheta

2020-10-19 16:00 UTC, roke77 approved these changes

2020-10-19 16:06 UTC, nahudalla commented on src/models/person.js
> +  Person.associate = (models) => {
Missing association with `user` and physical address with `person`. For the last one, I don't know how to indicate to Sequelize (even, if it's necessary) that an association may not be available (the address may not be associated to a person, but the person does have one or more addresses).

2020-10-19 19:38 UTC, nahudalla requested changes

2020-10-19 19:38 UTC, nahudalla commented on src/models/person.js
> +    Person.belongsTo(models.user)
```suggestion
    Person.hasOne(models.user)
```
https://sequelize.org/master/manual/assocs.html
> The A.hasOne(B) association means that a One-To-One relationship exists between A and B, with the foreign key being defined in the target model (B).
> 
> The A.belongsTo(B) association means that a One-To-One relationship exists between A and B, with the foreign key being defined in the source model (A).

2020-10-19 20:33 UTC, abelosorio approved these changes

2020-10-21 18:55 UTC, nahudalla approved these changes

2020-10-21 18:56 UTC, merged