Mp/add payout method interface
WeDevelop-ARG/cg-backend pull request #70
Opened 2020-10-28 19:14 UTC by MPucheta

2020-10-29 15:47 UTC, roke77 commented on src/controllers/business/index.js
> +  const payoutMethod = await models.business.findByPk(payoutMethodId)
`models.business` again? C&P mistake, right?

2020-10-29 15:48 UTC, roke77 commented on src/controllers/business/index.js
> +  return await business.setDefaultPayoutMethod(payoutMethod)
I think the `await` is no necessary here

2020-10-29 22:05 UTC, roke77 approved these changes

2020-10-30 12:43 UTC, nahudalla requested changes

2020-10-30 12:43 UTC, nahudalla commented on src/schema/types/business.graphql
> +  setDefaultPayoutMethod(businessId: ID!, payoutMethodId: ID!): Boolean!
This should be part of an `updateBusiness` mutation:
```graphql
input UpdateBusinessInput {
  id: ID!
  defaultPayoutMethodId: ID
}
extend type Mutation {
  updateBusiness(input: UpdateBusinessInput!): Business!
}
```

2020-10-31 00:07 UTC, nahudalla approved these changes

2020-10-31 00:07 UTC, merged